CC = gcc
CFLAGS = -Wall

all: snprintf strncpy sscanf strcasecmp strtok strcat strchr strstr str2num gets

snprintf: snprintf.c
	$(CC) $(CFLAGS) $< -o $@

strncpy: strncpy.c
	$(CC) $(CFLAGS) $< -o $@

sscanf: sscanf.c
	$(CC) $(CFLAGS) $< -o $@

strcasecmp: strcasecmp.c
	$(CC) $(CFLAGS) $< -o $@

strtok: strtok.c
	$(CC) $(CFLAGS) $< -o $@

strcat: strcat.c
	$(CC) $(CFLAGS) $< -o $@

strchr: strchr.c
	$(CC) $(CFLAGS) $< -o $@

strstr: strstr.c
	$(CC) $(CFLAGS) $< -o $@

str2num: str2num.c
	$(CC) $(CFLAGS) $< -o $@

gets: gets.c
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -f snprintf strncpy sscanf strcasecmp strtok strcat strchr strstr str2num gets
